global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blacked'
    static_configs:
      - targets: ['blacked:8082']
    metrics_path: '/metrics'
    
  - job_name: 'blacked-otel'
    static_configs:
      - targets: ['blacked:8082']
    metrics_path: '/otel-metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
